packages:
  global: !include packages/global.yaml
  esp32: !include packages/esp32-d1_mini32.yaml
  bt-proxy: !include packages/bt-proxy.yaml

esp32:
  framework:
    type: esp-idf

substitutions:
  slug: bt-proxy-main
  name: Bluetooth Proxy Main
