packages:
  global: !include packages/global.yaml
  wifi: !include packages/wifi.yaml

esp32:
  board: esp-wrover-kit

substitutions:
  slug: outdoor-patio-outlet
  name: Outdoor Patio Outlet

switch:
  - platform: gpio
    name: Twinkle Lights
    pin:
      number: GPIO15
      inverted: false
    id: relay1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led

  - platform: gpio
    name: Nectar Heater
    pin:
      number: GPIO32
      inverted: false
    id: relay2
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio

  - platform: gpio
    pin: GPIO16
    inverted: True
    id: relay2_led_gpio

light:
  - platform: binary
    name: Twinkle Lights LED
    id: relay1_led
    internal: true    
    output: relay1_led_gpio
    
  - platform: binary
    name: Nectar Warmer LED
    id: relay2_led
    internal: true
    output: relay2_led_gpio

sensor:
  - platform: total_daily_energy
    name: Energy
    power_id: power

  - platform: adc
    pin: GPIO34
    name: LUX
    update_interval: 10s
    attenuation: 11db

  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: 0.001
    voltage_divider: 770
    change_mode_every: 3
    update_interval: 3s    
    current:
      name: Amps
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: Volts
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: Watts
      id: power
      unit_of_measurement: kW
      accuracy_decimals: 0    
      filters:
        - multiply: 0.001
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58 

binary_sensor:
  - platform: gpio
    name: Twinkle Lights Button
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: True
    on_press:
      - switch.toggle: relay1

  - platform: gpio
    name: Nectar Warmer Button
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: True
    on_press:
      - switch.toggle: relay2

status_led:
  pin:
    number: GPIO5
    inverted: true

time:
  - platform: sntp