packages:
  global: !include packages/global.yaml
  s31: !include packages/sonoff-S31.yaml

esp8266:
  board: esp8285
  restore_from_flash: true

substitutions:
  topic_prefix: "esphome"
  slug: "outlet_energy_001"
  name: "Outlet Energy 001"

logger:
  baud_rate: 0