<<: !include templates/global.yaml
<<: !include templates/sonoff-S31.yaml

substitutions:
  topic_prefix: "esphome"
  slug: "outlet_energy_001"
  name: "Outlet Energy 001"

esphome:
  name: "${slug}"

esp8266:
  board: esp8285
  restore_from_flash: true

logger:
  level: info
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: total_daily_energy
    name: "${name} Energy"
    power_id: power

  - platform: cse7766
    update_interval: 15s
    current:
      name: "${name} Current"
      filters:
        - sliding_window_moving_average:
            window_size: 4
            send_every: 4
    voltage:
      name: "${name} Voltage"
      filters:
        - sliding_window_moving_average:
            window_size: 4
            send_every: 4
    power:
      name: "${name} Power"
      id: power
      unit_of_measurement: kW
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
        - sliding_window_moving_average:
            window_size: 4
            send_every: 4
binary_sensor:
  - platform: gpio
    id: btn_sensor
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: relay
  
  - platform: status
    name: "${name} Status"

switch:
  - platform: gpio
    name: "${name}"
    id: relay
    icon: "mdi:toggle-switch"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_ON

  - platform: restart
    name: ${name} Restart

status_led:
  pin: GPIO13

time:
  - platform: sntp
