packages:
  global: !include packages/global.yaml
  wifi: !include packages/coast-wifi.yaml
  esp32: !include packages/esp32-xiao-s3.yaml
  sen66: !include packages/sen66.yaml

substitutions:
  slug: coast-air-quality-main
  name: Coast Air Quality Main
