esphome:
  name: ${slug}

esp8266:
  board: d1_mini

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

logger:
  baud_rate: 0
  level: info

sensor:
  - platform: senseair
    co2:
      name: ${name}
    update_interval: 60s

binary_sensor:   
  - platform: status
    name: ${name} Status
    
button:
  - platform: restart
    name: ${name} Restart
