name: Build Firmware(s)

on:
  push:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build ESPHome binary for ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - bed.yaml
          - co2-bedrooms.yaml
          - co2-main.yaml
          - co2-office.yaml
          - fireplace.yaml
          - garage.yaml
          - outdoor-patio-outlets.yaml
          - outdoor-patio-shades.yaml
          - outlet-002.yaml
          - outlet-003.yaml
          - outlet-energy-001.yaml
          - pet-outlet.yaml
          - treat-dispenser.yaml
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt Secrets
        env:
          SECRET_YAML: ${{ secrets.SECRET_YAML }}
        run: |
          echo "$SECRET_YAML" > templates/secrets.yaml
      - uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: ${{ matrix.file }}
          version: latest
      - run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/
      - uses: actions/upload-artifact@v3
        with:
          name: esphome
          path: output

  publish:
    name: Publish new firmware and website to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: output
          name: esphome

      - name: Create single manifest.json
        run: |
          jq -s '{"name": "esphome", "version": "${{ needs.build.outputs.esphome-version }}", "home_assistant_domain": "esphome", "new_install_skip_erase": false, "builds":.}' output/*/manifest.json > output/manifest.json

      - run: cp -R static/* output

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output
          clean: true
